function H = OperatorFromKernel(h, im_size, im_size_pad, H_blocks)
% Given a 2D convolution kernel "h" and the size of the target image, the
% function returns the the operator (H) that works on the linearized version of
% the image.
% If the size is to big, H is the set of matrixes that form the operator.
% The image is considered to be linearized by concatenating the COLUMNS.
% TODO: 
%   *Correct the asymmetry generated by the assumption of superposition
%   *Work for kernels that are even and odd in shape

h_s = size(h);

h_cols = [h; zeros(im_size_pad(1)-1,h_s(2))];
c = reshape(h_cols, size(h_cols,1)*size(h_cols,2), 1);

c = [c; zeros((length(c)/h_s(2))*(im_size(2)-h_s(2)), 1)];

if (max(im_size) < 200)
    'Toeplitz version'
    r = [h(1,1) zeros(1, im_size(1)*im_size(2) - 1)];
    H = toeplitz(c, r);
else
    'Iterative version (TODO)'
%     H = zeros(im_size(1)*im_size(2),im_size(1)*im_size(2)/H_blocks , H_blocks);
%     for i = 1:(im_size(1)*im_size(2))
%         H(i,:,j) = r;
%     end
end


end

