function H = OperatorFromKernel(h, im_size, H_blocks)
% Given a 2D convolution kernel "h" and the size of the target image, the
% function returns the the operator (H) that works on the linearized version of
% the image.
% If the size is to big, H is the set of matrixes that form the operator.
% The image is considered to be linearized by concatenating the COLUMNS.
% TODO: 
%   *Correct the asymmetry generated by the assumption of superposition
%   *Work for kernels that are even and odd in shape

h_s = size(h);

%Toeplitz precisa ser montado com o filtro completo, logo, precisamos
%truncar a matriz final.

h_pad = [h; zeros(im_size(1)-h_s(1),h_s(2))];
r = reshape(h_pad, im_size(1)*h_s(2), 1)';
r = [r zeros(1, (im_size(2)-h_s(2))*im_size(1))];

if (max(im_size) < 200)
    'Toeplitz version'
    c = [h(1,1); zeros(im_size(1)*im_size(2) - 1, 1)];
    H = toeplitz(c, r);
else
    'Iterative version'
%     H = zeros(im_size(1)*im_size(2),im_size(1)*im_size(2)/H_blocks , H_blocks);
%     for i = 1:(im_size(1)*im_size(2))
%         H(i,:,j) = r;
%     end
end


end

